# Slexion 短路径重写规则
rewrite ^/home$ /home/home.html last;
rewrite ^/home_en$ /home/home_en.html last;
rewrite ^/vlog$ /vlog/vlog.php last;
rewrite ^/feedback$ /feedback/feedback.html last;
rewrite ^/browser$ /slexionbrowser/AboutSlexionBrowser.html last;
rewrite ^/clock$ /macosclock/AboutmacOSClock.html last;
rewrite ^/games$ /littlegames/lg.html last;
rewrite ^/snake$ /littlegames/snake.html last;
rewrite ^/beastplay$ /littlegames/BeastPlay.html last;
rewrite ^/download$ /download/download_slexionbrowser.html last;
rewrite ^/dlsi$ /download/dlsi/dlsi.html last;
rewrite ^/404$ /404.html last;
